// I created this C# record to represent the AI task generation request
// I'm using a record because it's immutable and perfect for DTOs (Data Transfer Objects)
// Records in C# 9+ give me automatic equality comparison and deconstruction

namespace TasclyBackend.API.Models;

// I'm using the record keyword which creates an immutable reference type
// This is perfect for request/response objects that shouldn't change after creation
public record AiTaskRequest(
    // I'm storing the natural language prompt from the manager
    // This is what the AI will analyze to generate tasks
    string Prompt,
    
    // I need to know which project these tasks belong to
    // This helps provide context to the AI about the project
    int ProjectId,
    
    // I'm tracking the current application mode (Business vs Project)
    // This allows the AI to tailor tasks for Hospitality/Office vs Software/Technical
    string Mode,

    // I'm tracking who made the request for audit purposes
    // This also helps personalize the AI responses based on user preferences
    int UserId
);

// I created this class to represent a single draft task from the AI
// This is what the AI returns before the tasks are saved to the database
public class DraftTask
{
    // I'm using a temporary ID to track tasks in the frontend
    // This isn't a database ID yet, just for UI management
    // Using long because JavaScript Date.now() returns timestamps that exceed int.MaxValue
    public long TempId { get; set; }
    
    // The AI generates these core task properties
    public string Title { get; set; } = string.Empty;
    
    public string Description { get; set; } = string.Empty;
    
    // I'm using strings for priority and type to match the frontend
    // I'll convert these to enums when saving to the database
    public string Priority { get; set; } = string.Empty;
    
    public decimal EstimatedHours { get; set; }
    
    // The AI suggests an assignee based on team member skills
    // I made this nullable because not all tasks need immediate assignment
    public string? SuggestedAssignee { get; set; }
    
    public string Type { get; set; } = string.Empty;

    // Temporal fields allowing the AI to specify when tasks should occur
    public DateTime? ScheduledStart { get; set; }
    public DateTime? DueDate { get; set; }
}

// I created this class for the bulk task creation request
// This is sent when the user approves the draft tasks
public class BulkTaskCreateRequest
{
    // The list of tasks that have been reviewed and approved
    // The user may have edited these from the AI's original suggestions
    public List<DraftTask> Tasks { get; set; } = new();
    
    // Which project these tasks should be created in
    public int ProjectId { get; set; }
}

// I created this record for the AI's response
// This wraps the draft tasks with additional metadata
public record AiTaskResponse(
    // The array of draft tasks generated by the AI
    List<DraftTask> Tasks,
    
    // I'm including a confidence score so users know how sure the AI is
    // This helps them know if they should review more carefully
    double? Confidence,
    
    // Any notes or warnings from the AI that users should see
    // For example, if the prompt was ambiguous or missing information
    string? Notes
);
